name: Ping
run-name: "Ping: Issue #${{ github.event.inputs.issue-number }}"

on:
  workflow_dispatch:
    inputs:
      issue-number:
        description: Issue number
        required: true
      comment-id:
        description: Comment ID
        required: true

permissions:
  issues: write
  contents: read

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Reply with pong
        uses: peter-evans/create-or-update-comment@v5
        with:
          issue-number: ${{ github.event.inputs.issue-number }}
          body: |
            Pong!